### ISSUE TITLE
Duplicate states

### ISSUE THREAD

**Issue by mp1pro** [jarellbennett/Jammming#3]
The initial states set up in the constructor of the playList class was already set up in app.js. Hence we can remove this in playList.js;
```

this.state ={
      playlistName: 'New Playlist',
      playlistTracks: []
}
```

**Comment by jarellbennett** [comment]
I didn't have it before but, the adviser on the slack channel told me to add it.

**Comment by jarellbennett** [comment]
I'll remove it
